server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/ymsproject
    username: root
    password: 123456
mybatis:
  type-aliases-package: com.ymsd.entity